[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-mios-version-min=18.4"]

[target.aarch64-apple-ios-sim]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=18.4"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-mios-simulator-version-min=18.4"]