[package]
name = "dialog_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
dialog_lib = { path = "../dialog_lib" }
nostr-sdk = { version = "0.37", features = ["ndb", "nip44"] }
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
thiserror = "2"
