[package]
name = "dialog_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
dialog_lib = { path = "../dialog_lib" }
nostr-sdk = { workspace = true }
clap = { version = "4", features = ["derive"] }
tokio = { workspace = true }
thiserror = { workspace = true }
