import Foundation
import Dialog

// Note struct is now generated by UniFFI
// This file extends it with UI helpers

extension Note: Identifiable {
    // id property already exists from UniFFI
}

// Note already conforms to Hashable from UniFFI generation

extension Note {
    // UI helpers
    var displayTags: [String] {
        tags.map { "#\($0)" }
    }
    
    var relativeTime: String {
        // createdAt is now a UInt64 timestamp in seconds
        let date = Date(timeIntervalSince1970: TimeInterval(createdAt))
        let formatter = RelativeDateTimeFormatter()
        formatter.unitsStyle = .abbreviated
        return formatter.localizedString(for: date, relativeTo: Date())
    }
    
    // Convert timestamp to Date for UI use
    var createdAtDate: Date {
        Date(timeIntervalSince1970: TimeInterval(createdAt))
    }
}