name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
    
    - name: Setup nak with GiftWrap support
      run: |
        # Clone nak
        git clone https://github.com/fiatjaf/nak.git /tmp/nak
        cd /tmp/nak
        
        # Apply our patch if it exists
        if [ -f "$GITHUB_WORKSPACE/nak-giftwrap.patch" ]; then
          git apply "$GITHUB_WORKSPACE/nak-giftwrap.patch"
        fi
        
        # Build nak
        go build -o $GITHUB_WORKSPACE/dialog_lib/nak-negentropy .
        chmod +x $GITHUB_WORKSPACE/dialog_lib/nak-negentropy
    
    - name: Run tests
      working-directory: dialog_lib
      env:
        DIALOG_DATA_DIR: ${{ runner.temp }}/dialog-${{ github.run_id }}
      run: cargo test --verbose -- --test-threads=1 --nocapture
    
    - name: Run clippy
      working-directory: dialog_lib
      run: cargo clippy -- -D warnings
    
    - name: Check formatting
      working-directory: dialog_lib
      run: cargo fmt -- --check
    
    - name: Build CLI
      working-directory: dialog_cli
      run: cargo build --release
    
    - name: Test CLI persistence
      env:
        DIALOG_DATA_DIR: ${{ runner.temp }}/dialog-${{ github.run_id }}
        DIALOG_NSEC: nsec1ufnus6pju578ste3v90xd5m2decpuzpql2295m3sknqcjzyys9ls0qlc85
      run: |
        chmod +x test_cli_persistence.sh
        ./test_cli_persistence.sh